services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Wexample\SymfonyAi\:
        resource: '../../{Controller,Form,Repository,Service}'

    Wexample\SymfonyAi\Api\Controller\:
        resource: '../../Api/Controller/*'
        tags: ['controller.service_arguments']

    Wexample\SymfonyAi\Api\Normalizer\:
        resource: '../../Api/Normalizer/*'
        tags: ['serializer.normalizer']
